/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { BodyMeasurementService } from "../bodyMeasurement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BodyMeasurementCreateInput } from "./BodyMeasurementCreateInput";
import { BodyMeasurementWhereInput } from "./BodyMeasurementWhereInput";
import { BodyMeasurementWhereUniqueInput } from "./BodyMeasurementWhereUniqueInput";
import { BodyMeasurementFindManyArgs } from "./BodyMeasurementFindManyArgs";
import { BodyMeasurementUpdateInput } from "./BodyMeasurementUpdateInput";
import { BodyMeasurement } from "./BodyMeasurement";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BodyMeasurementControllerBase {
  constructor(
    protected readonly service: BodyMeasurementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BodyMeasurement })
  @nestAccessControl.UseRoles({
    resource: "BodyMeasurement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: BodyMeasurementCreateInput
  ): Promise<BodyMeasurement> {
    return await this.service.create({
      data: {
        ...data,

        users: data.users
          ? {
              connect: data.users,
            }
          : undefined,
      },
      select: {
        chest: true,
        createdAt: true,
        id: true,
        leftArm: true,
        leftLeg: true,
        measurementTime: true,
        rightArm: true,
        rightLeg: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },

        waist: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [BodyMeasurement] })
  @ApiNestedQuery(BodyMeasurementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BodyMeasurement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<BodyMeasurement[]> {
    const args = plainToClass(BodyMeasurementFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        chest: true,
        createdAt: true,
        id: true,
        leftArm: true,
        leftLeg: true,
        measurementTime: true,
        rightArm: true,
        rightLeg: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },

        waist: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BodyMeasurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BodyMeasurement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: BodyMeasurementWhereUniqueInput
  ): Promise<BodyMeasurement | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        chest: true,
        createdAt: true,
        id: true,
        leftArm: true,
        leftLeg: true,
        measurementTime: true,
        rightArm: true,
        rightLeg: true,
        updatedAt: true,

        users: {
          select: {
            id: true,
          },
        },

        waist: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BodyMeasurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BodyMeasurement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: BodyMeasurementWhereUniqueInput,
    @common.Body() data: BodyMeasurementUpdateInput
  ): Promise<BodyMeasurement | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          users: data.users
            ? {
                connect: data.users,
              }
            : undefined,
        },
        select: {
          chest: true,
          createdAt: true,
          id: true,
          leftArm: true,
          leftLeg: true,
          measurementTime: true,
          rightArm: true,
          rightLeg: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },

          waist: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BodyMeasurement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "BodyMeasurement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: BodyMeasurementWhereUniqueInput
  ): Promise<BodyMeasurement | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          chest: true,
          createdAt: true,
          id: true,
          leftArm: true,
          leftLeg: true,
          measurementTime: true,
          rightArm: true,
          rightLeg: true,
          updatedAt: true,

          users: {
            select: {
              id: true,
            },
          },

          waist: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
